---
title: "Wrangle"
author: "Avinash"
date: '2018-02-20'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r}
library(tidyr)
library(dplyr)
library(forcats)
library(purrr)
library(feather)
library(plotly)
library(stringi)
library(leaflet)
library(rgdal)
library(readr)
```

```{r}

#https://ucr.fbi.gov/ucr-publications

counties <- map_data("county") %>% group_by(region, subregion) %>% summarise()

cleaner <- function(year){

df <- read.csv(paste("../data/csv/",year ,".csv",sep = ""), header = FALSE)

names(df) <- c("region", "city", "violent_crime", "homs_sum", "RapeRevised", "RapeLegacy", "rob_sum", "agg_ass_sum", "PropertyCrime", "Burglary", "Larceny", "MotorVehicleTheft", "Arson")

df_1 <- df %>% separate(region, into = c("region", "type"), sep = " - ")


for (i in 1:nrow(df_1)){
if(df_1[i,1] == ""){
  df_1[i,1] <-  df_1[i-1,1]
}
if(is.na(df_1[i,2])){
  df_1[i,2] <-  df_1[i-1,2]
}}

df_1$city <- gsub('[[:digit:]]+', '', df_1$city)
df_1$city <- gsub(', ', '', df_1$city)
df_1$type <- gsub('[[:digit:]]+', '', df_1$type)
df_1$region <- stringi::stri_trans_tolower(df_1$region)
df_1$city <- stringi::stri_trans_tolower(df_1$city)

df_1 <- df_1 %>% rowwise() %>% mutate(rape_sum = sum(as.numeric(RapeRevised),as.numeric(RapeLegacy), na.rm = TRUE))

df_2 <- df_1 %>% select(c(1:5, 8:15))

df_2 <- inner_join(counties, df_2, by = c("region" = "region", "subregion" = "city"))

df_2$region <- stringi::stri_trans_totitle(df_2$region)

df_2 <- df_2 %>% mutate(year = year) %>% rowwise() %>% 
          mutate(violent_crime = sum(homs_sum, rob_sum, agg_ass_sum, rape_sum, na.rm = TRUE))

names(df_2)[2] <- "city"

feather::write_feather(df_2, paste("../results/", year, ".feather", sep = ""))

return(df_2)

}


```


```{r}

year <-  2008

cleaner_new <- function(year){

df <- read.csv(paste("../data/csv/",year ,".csv",sep = ""), header = FALSE)

names(df) <- c("region", "city", "violent_crime", "homs_sum", "rape_sum", "rob_sum", "agg_ass_sum", "PropertyCrime", "Burglary", "Larceny", "MotorVehicleTheft", "Arson")

if(year == 2011) {
  df <- df[1:12]
}

df_1 <- df %>% separate(region, into = c("region", "type"), sep = "")


for (i in 1:nrow(df_1)){
if(df_1[i,1] == ""){
  df_1[i,1] <-  df_1[i-1,1]
}
if(is.na(df_1[i,2])){
  df_1[i,2] <-  df_1[i-1,2]
}}

df_1$city <- gsub('[[:digit:]]+', '', df_1$city)
df_1$city <- gsub(', ', '', df_1$city)
df_1$type <- gsub('[[:digit:]]+', '', df_1$type)
df_1$region <- stringi::stri_trans_tolower(df_1$region)
df_1$city <- stringi::stri_trans_tolower(df_1$city)

#df_2 <- df_1 %>% select(c(1:5, 8:15))

df_2 <- inner_join(counties, df_1, by = c("region" = "region", "subregion" = "city"))

df_2$region <- stringi::stri_trans_totitle(df_2$region)

df_2 <- df_2 %>% mutate(year = year) %>% rowwise() %>% 
          mutate(violent_crime = sum(homs_sum, rob_sum, agg_ass_sum, rape_sum, na.rm = TRUE))

names(df_2)[2] <- "city"

feather::write_feather(df_2, paste("../results/", year, ".feather", sep = ""))

return(df_2)

}


#c(2016) %>% map_df(cleaner)

d16 <- cleaner(2016)
d15 <- cleaner(2015)
d14 <- cleaner(2014)
d13 <- cleaner(2013)
d12 <- cleaner_new(2012)
d11 <- cleaner_new(2011)
d10 <- cleaner_new(2010)
d09 <- cleaner_new(2009)

crime <- rbind(d16, d15, d14, d13, d12, d11, d10, d09)

codes <- read.csv(file ="../results/codes.csv")

# codes <- codes %>% mutate(region = as.character(region))

crime <- left_join(crime, codes)

crime <- crime %>% mutate(code = as.character(code))

feather::write_feather(crime, "../results/crime.feather")


geo_data <- readOGR("../data/shc/cb_2016_us_county_20m.shp",
                       layer = "cb_2016_us_county_20m", GDAL1_integer64_policy = TRUE)

geodata <- geo_data@data

geocode <- read_csv("../data/geocode.csv")

geodata <- geodata %>% mutate(GEOID = as.character(GEOID)) %>% mutate(GEOID = as.numeric(GEOID))

first <- left_join(geodata, geocode, by = c("GEOID" = "X2"))

first <- first %>% mutate(NAME = stringi::stri_trans_tolower(NAME))

#geo_data@data <- first

#write_csv(first, "../data/codes.csv")

crime1 <- crime %>% mutate(code = as.character(code)) %>% filter(year %in% c(2016))

second <- left_join(first, crime1, by = c("code", "NAME" = "city"))

geo_data@data <- second

x <- NA

if_else(is.na(x), 2, 3)

df %>% mutate(region = as.character(region)) %>% separate(region, into = c("region", "type"), sep = " - ")
  


df[1:12]

```


```{r}
y <- "violent_crime"

crime %>% filter(y > 10)
```

```{r}

     geo_data$violent_crime <- as.numeric(geo_data$violent_crime)     

     geo_data$violent_crime[is.na(geo_data$violent_crime)] <- 0
     
     neStates <- subset(geo_data, geo_data$code == x$code)
     
     pal <- colorNumeric("viridis", NULL)
     
     leaflet(neStates) %>% addTiles() %>% 
       addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
                   opacity = 1.0, fillOpacity = 1,
                   fillColor = ~pal(violent_crime),
                   label = ~paste(violent_crime),
                   highlightOptions = highlightOptions(color = "white", weight = 2,
                                                       bringToFront = TRUE)) %>% 
       addLegend(pal = pal, values = ~violent_crime, opacity = 1.0)
```

```{r}
geo_data@data
geo_data$ALAND

states@data
```

```{r}
data <- read_tsv("../data/neigh.csv",col_names = FALSE)

new_df <- data_frame()
i <- 1
for (i in 1:nrow(data)) {
  
  if (!is.na(data[i,1])) {
    new_df <- bind_rows(new_df, data[i,])
  }
}

new_df <- new_df %>% select(X1, X2)

new_df <- new_df %>% separate(X1, into = c("city", "code"), sep = ", ")

new_df <- new_df %>% mutate(X2 = as.numeric(X2))

new_df <- new_df

write_csv(new_df,"../data/geocode.csv")
```


```{r}
test$city <- gsub('[[:digit:]]+', '', test$city)
test$city <- gsub(', ', '', test$city)
test$city

new <- counties %>% group_by(region) %>% summarise() %>% arrange() %>% as.list()
crime

match("new york", new$region)
```


```{r}
test <- crime %>% filter(region == "California", year == 2014) %>% mutate(violent_crime = as.integer(violent_crime))%>% select(city, violent_crime) %>% arrange(city)
test$city <- gsub('[[:digit:]]+', '', test$city)
test$city <- gsub(', ', '', test$city)
#test <- test %>% mutate(city = stringi::stri_trans_tolower(city))
test <- rbind(test, c("san francisco",0))
```

```{r}
df <- crime %>% filter(region == "California", year == 2014)

state <- map_data("county") %>%
  filter(region == "california")

# pop <- df %>%
#   group_by(County.Name) %>%
#   summarise(Pop = sum(Population))

#pop$County.Name <- tolower(pop$County.Name) # matching string

state_df <- merge(state, df, by.x = "subregion", by.y = "city")

state_df <- state_df  %>% mutate(violent_crime = as.numeric(violent_crime))

value <- max(state_df$violent_crime, na.rm = TRUE)/ 11

state_df$breaks <- cut(state_df$violent_crime, breaks = c(seq(0, max(state_df$violent_crime, na.rm = TRUE), by = value)), labels=1:11)

print(state_df$breaks)

p <- state_df %>%
  group_by(group) %>%
  plot_ly(x = ~long, y = ~lat, color = ~breaks, colors = c('#ffeda0','#f03b20'),
          text = ~subregion, hoverinfo = 'text') %>%
  add_polygons(line = list(width = 0.4)) %>%
  add_polygons(
    fillcolor = 'transparent',
    line = list(color = 'black', width = 0.5),
    showlegend = FALSE, hoverinfo = 'none'
  ) %>%
  layout(
    title = "California Population by County",
    titlefont = list(size = 10),
    xaxis = list(title = "", showgrid = FALSE,
                 zeroline = FALSE, showticklabels = FALSE),
    yaxis = list(title = "", showgrid = FALSE,
                 zeroline = FALSE, showticklabels = FALSE)
  )

p

```

```{r}
# df <- crime %>% filter(region == "California", year == 2014)

state <- map_data("county") %>%
  filter(region == "california")

# pop <- df %>%
#   group_by(County.Name) %>%
#   summarise(Pop = sum(Population))

#pop$County.Name <- tolower(pop$County.Name) # matching string

state_df <- merge(state, test, by.x = "subregion", by.y = "city")

state_df <- state_df  %>% mutate(violent_crime = as.numeric(violent_crime))

value <- max(state_df$violent_crime)/ 11

state_df$breaks <- cut(state_df$violent_crime, breaks = c(seq(0, max(state_df$violent_crime), by = value)), labels=1:11)

print(state_df$breaks)

p <- state_df %>%
  group_by(group) %>%
  plot_ly(x = ~long, y = ~get("lat"), color = ~breaks, colors = c('#ffeda0','#f03b20'),
          text = ~subregion, hoverinfo = 'text') %>%
  add_polygons(line = list(width = 0.4)) %>%
  add_polygons(
    fillcolor = 'transparent',
    line = list(color = 'black', width = 0.5),
    showlegend = FALSE, hoverinfo = 'none'
  ) %>%
  layout(
    title = "California Population by County",
    titlefont = list(size = 10),
    xaxis = list(title = "", showgrid = FALSE,
                 zeroline = FALSE, showticklabels = FALSE),
    yaxis = list(title = "", showgrid = FALSE,
                 zeroline = FALSE, showticklabels = FALSE)
  )

p

```



13/5/2018

Releveling for plotly

```{r}
pre_dat <- crime %>%
  group_by(region, year) %>% 
  summarise(custom = sum(violent_crime, na.rm = TRUE)) %>% spread("year", "custom") %>%
  arrange(get("2014")) %>% tail()

dat <- pre_dat %>% gather("year", "custom", 2:4)



dat$region <- factor(dat$region, levels = rev(pre_dat$region))

dat %>% ggplot() + geom_line(aes(year, custom, group = region, color = region))
```

```{r}
crime %>% filter(region == x$region, year == 2014) %>% 
  select(region, city, year, violent_crime) %>% 
  spread("year", "violent_crime") %>% 
        arrange(`2014`) %>% 
        head() %>% 
        mutate(city = str_to_title(city)) %>% 
        group_by(city) %>% summarise() %>% as.list()


crime %>% filter(region == "Texas", year == 2014) %>%
        arrange(violent_crime) %>% 
        head() %>% 
        mutate(city = str_to_title(city)) %>% 
        group_by(city) %>% summarise() %>% as.list()
```


```{r}
library(plotly)

data <- crime %>% filter(region == "Texas", year == 2014) %>% rowwise() %>% 
  mutate(violent_crime = sum(homs_sum, rob_sum, agg_ass_sum, rape_sum, na.rm = TRUE)) %>% 
        arrange(violent_crime) %>% 
        tail(na.rm = TRUE) %>% 
        mutate(city = str_to_title(city))

plot_ly(data, x = ~city, y = ~homs_sum, type = 'bar', name = 'Homicide') %>%
  add_trace(y = ~rape_sum, name = 'Rape') %>%
  layout(yaxis = list(title = 'Count'), barmode = 'stack')

```
```{r, message=FALSE, warning=FALSE}
 pre_plot_data <- crime %>% filter(year == 2014) %>% rowwise() %>% 
  mutate(violent_crime = sum(homs_sum, rob_sum, agg_ass_sum, rape_sum, na.rm = TRUE)) %>% 
          arrange(violent_crime) %>% tail(10) 

      plot_data <- pre_plot_data
      plot_data$city <- factor(plot_data$city, levels = rev(pre_plot_data$city))
 
      xtitle = "A"
      title = "B"
      plot_ly(plot_data, x = ~city, y = ~agg_ass_sum, type = 'bar', name = 'Assault', text = ~agg_ass_sum,
              textposition = 'auto',
             marker = list(line = list(color = 'rgb(8,48,107)', width = 1.5))) %>%
        add_trace(y = ~rob_sum, name = 'Robbery', text = ~rob_sum,
              textposition = 'auto',
             marker = list(line = list(color = 'rgb(8,48,107)', width = 1.5))) %>%
        add_trace(y = ~rape_sum, name = 'Rape', text = ~rape_sum,
              textposition = 'auto',
             marker = list(line = list(color = 'rgb(8,48,107)', width = 1.5))) %>%
        add_trace(y = ~homs_sum, name = 'Homicide', text = ~homs_sum,
              textposition = 'auto',
             marker = list(line = list(color = 'rgb(8,48,107)', width = 1.5))) %>%
        layout(yaxis = list(title = 'Count'), barmode = 'stack') %>% 
        layout(title =  ~paste("Violent crimes in ", "SF"), font = f, 
               xaxis = list(title = paste("Counties"), titlefont = f, tickfont = f),
               yaxis = list(title = "Violent Crimes", titlefont = f, titlefont = f),
               legend = list(font = f),showlegend = TRUE)
```

```{r}
 pre_plot_data <- crime %>% filter(year == 2014) %>% rowwise() %>% 
  mutate(violent_crime = sum(homs_sum, rob_sum, agg_ass_sum, rape_sum, na.rm = TRUE)) %>% 
  group_by(region) %>% summarise(violent_crime = sum(violent_crime, na.rm = TRUE), homs_sum = sum(homs_sum, na.rm = TRUE), rob_sum = sum(rob_sum, na.rm = TRUE), agg_ass_sum = sum(agg_ass_sum, na.rm = TRUE), rape_sum = sum(rape_sum, na.rm = TRUE)) %>% 
          arrange(violent_crime) %>% tail(10) 

      plot_data <- pre_plot_data
      plot_data$region <- factor(plot_data$region, levels = rev(pre_plot_data$region))
 
      xtitle = "A"
      title = "B"
      plot_ly(plot_data, x = ~region, y = ~agg_ass_sum, type = 'bar', name = 'Assault', text = ~agg_ass_sum,
              textposition = 'auto',
             marker = list(line = list(color = 'rgb(8,48,107)', width = 1.5))) %>%
        add_trace(y = ~rob_sum, name = 'Robbery', text = ~rob_sum,
              textposition = 'auto',
             marker = list(line = list(color = 'rgb(8,48,107)', width = 1.5))) %>%
        add_trace(y = ~rape_sum, name = 'Rape', text = ~rape_sum,
              textposition = 'auto',
             marker = list(line = list(color = 'rgb(8,48,107)', width = 1.5))) %>%
        add_trace(y = ~homs_sum, name = 'Homicide', text = ~homs_sum,
              textposition = 'auto',
             marker = list(line = list(color = 'rgb(8,48,107)', width = 1.5))) %>%
        layout(yaxis = list(title = 'Count'), barmode = 'stack') %>% 
        layout(title =  ~paste("Violent crimes in ", "SF"), font = f, 
               xaxis = list(title = paste("Counties"), titlefont = f, tickfont = f),
               yaxis = list(title = "Violent Crimes", titlefont = f, titlefont = f),
               legend = list(font = f),showlegend = TRUE)
```

